name: CI/CD Pipeline to AKS

on:
  push:
    branches:
      - main # Triggers on push to the main branch

env:
  AZURE_CONTAINER_REGISTRY: ph3containerregistry.azurecr.io
  RESOURCE_GROUP: Phase3-RG
  CLUSTER_NAME: Phase3-AKS-Cluster
  IMAGE_NAME: static-site-app
  
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout Code
      - uses: actions/checkout@v4

      # 2. Azure Login using the Secret
      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      # 3. Docker Login (Log in to your ACR)
      - name: Docker Login to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.AZURE_CONTAINER_REGISTRY }}
          username: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }} # FIXED SYNTAX
          password: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }} # Using clientSecret as password for ACR logi

          

      # 4. Build and Push Image (Using the commit SHA as the tag)
      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      # 5. Get AKS Credentials (Set up kubectl)
      - name: Set up kubectl context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ env.RESOURCE_GROUP }}
          cluster-name: ${{ env.CLUSTER_NAME }}
          
      # 6. Deployment: Update the YAML to use the new SHA tag
      - name: Update Kubernetes Deployment File with new image
        run: |
          # Use 'sed' to replace the 'v1' tag with the unique commit SHA for the new image
          sed -i "s|ph3containerregistry.azurecr.io/static-site-app:v1|${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}|g" phase3_iac/deployment.yaml

      # 7. Deployment: Apply the updated manifest
      - name: Deploy to AKS
        run: kubectl apply -f phase3_iac/deployment.yaml
      

      # 8. Verification: Wait for deployment to stabilize
      - name: Verify Deployment Status
        run: kubectl rollout status deployment/static-site-deployment --timeout=5m
